//
//  PlayerInteractor.swift
//  DTTask
//
//  Created by Dima Tsurkan on 9/1/17.
//  Copyright (c) 2017 Dima Tsurkan. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PlayerBusinessLogic {
    func playVideo(request: Player.FetchVideo.Request)
}

protocol PlayerDataStore {
    var videoURL: String { get set }
}

class PlayerInteractor: PlayerBusinessLogic, PlayerDataStore {
    var presenter: PlayerPresentationLogic?
    var worker: PlayerWorker?
    var videoURL: String = "https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8"
  
    // MARK: Do something
  
    func playVideo(request: Player.FetchVideo.Request) {
        worker = PlayerWorker()
        worker?.doSomeWork()
    
        let response = Player.FetchVideo.Response(videoURL: URL(string: videoURL)!)
        presenter?.presentVideoPlayer(response: response)
    }
}
